name: Verifica estilos e roda testes

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configura o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verifica estilos e boas práticas
        run: |
          black --check --exclude "analysis" .
          flake8 --exclude analysis/ .
      - name: Executa os testes
        run: pytest
