name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Verifica se o Jupyter Notebook está limpo
      uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
