name: Converte Notebook para script Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configura o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: Instala o Jupyter
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
      - name: Gera scripts
        run: jupyter nbconvert --to script analysis/*.ipynb
      - name: Commita novos scripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Gera scripts Python"
          file_pattern: "*.py"
