name: Converte Notebook para script Python

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          jupyter nbconvert --to script analysis/*.ipynb
      - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install jupyter
            jupyter nbconvert --to script analysis/*.ipynb
      - name: Commita scripts
        uses: EndBug/add-and-commit@v4
        with:
          message: "Gera scripts Python"
          add: "*.py"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
